# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tei_tools',
                'doc_host': 'https://nakamura196.github.io',
                'git_url': 'https://github.com/nakamura196/tei_tools',
                'lib_path': 'tei_tools'},
  'syms': { 'tei_tools.api': { 'tei_tools.api.TeiTools': ('api.html#teitools', 'tei_tools/api.py'),
                               'tei_tools.api.TeiTools.__init__': ('api.html#teitools.__init__', 'tei_tools/api.py'),
                               'tei_tools.api.TeiTools.analyze': ('api.html#teitools.analyze', 'tei_tools/api.py'),
                               'tei_tools.api.TeiTools.analyzeDir': ('api.html#teitools.analyzedir', 'tei_tools/api.py'),
                               'tei_tools.api.TeiTools.hello_world': ('api.html#teitools.hello_world', 'tei_tools/api.py'),
                               'tei_tools.api.TeiTools.visualize': ('api.html#teitools.visualize', 'tei_tools/api.py')},
            'tei_tools.core': {'tei_tools.core.foo': ('core.html#foo', 'tei_tools/core.py')}}}