# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tei_tools',
                'doc_host': 'https://nakamura196.github.io',
                'git_url': 'https://github.com/nakamura196/tei_tools',
                'lib_path': 'tei_tools'},
  'syms': { 'tei_tools.api': {'tei_tools.api.foo': ('api.html#foo', 'tei_tools/api.py')},
            'tei_tools.core': {'tei_tools.core.foo': ('core.html#foo', 'tei_tools/core.py')}}}